apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    namespace: elog
type: Opaque
stringData:
    MONGO_DB_HOST: ENC[AES256_GCM,data:4/o8wsSnQF9bPcjBQ1WT1kxdUjgvZQCZ0P9WVuMV/uYhKDxF3i4=,iv:vRXG3rt9BPPUhetD1475XJ5ad2sI6fiy7FizoHLghuM=,tag:DVDm23nqfMxmxg1IdEIevw==,type:str]
    MONGO_DB_PORT: ENC[AES256_GCM,data:pPk5Ecc=,iv:srBEBAzozg+ZV3AkzSMG5KIrjS8mjcFSoEgCw1okgN8=,tag:twTmmW0l0ArsBUd4wSAD8w==,type:str]
    MONGO_USER: ENC[AES256_GCM,data:pJiBlMc=,iv:0mH+4HLIBg6RR0x/wUn4gcd54e10RQ8tlSo7qtgaQ9Q=,tag:AfYAIqTKXAGwrTgssnDF3w==,type:str]
    MONGO_PASSWORD: ENC[AES256_GCM,data:vDAAqKZy,iv:qXGW81Qcgo/pVM1gvxNja95Kx0Mtn3sTG013hMh5Pb4=,tag:CxcaXkBBU9vpU5cBv1l2AA==,type:str]
    MONGO_DB_NAME: ENC[AES256_GCM,data:2ayRX+Ny,iv:hYxBZCLK/hKJEjCt7+BE7cGSxNQabhLeoqiosB7YX4Y=,tag:c7G5+3DW5uU0JP0+5AayGQ==,type:str]
sops:
    age:
        - recipient: age1dns2gwpv07g83js3vuqazvlgrwzm78h75hd3xcxqrtwwmsdjsglsu42s0v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0R1BsRmx4TG4zdmoxcGQ2
            YkNBMXg4QWtWWS81WVpYM1lXbnZqc1BvZ1hBCkg3MWU2ckUxZ05tM1RCQWtHNnB2
            bi83ZUpuVU1DK3FKYjQ2NXRqR2habU0KLS0tIHAzSWkwclN6b1h2TUlDNk1KdC9p
            d2ptRHVoRXNmdGhyb3k5ZWw2WVV2QjgKACmK4L2VSFCpsStPbYGbx2DGLvXf3htK
            6erSZA1pFppSTmrm/MQbx3zfWutIWAIaHCv3unfTjZEvcVhifguTyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T16:36:55Z"
    mac: ENC[AES256_GCM,data:uYvfxHGDrghX0uI0o9zEJx2Bdxcz2Yb/k4FmX55WGRYCy3lhX69TkPCyhiGDnasVP90KsmGqix7jLryXfETU4xKvBpdn+IJPxM3IlPx+rxIpk9u+b/o4b8o2tbwx1lHXv79AfsZPCIad8KwqtzEb3GkGZSw/rlZkwoMojvYzkzk=,iv:0hsgN9wWpyiyZ/B34v53DwhxwwducJK85qauiw96j0A=,tag:2bb44hjGykW8ezPk517BNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
