apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    namespace: elog
type: Opaque
stringData:
    MONGO_DB_HOST: ENC[AES256_GCM,data:x2fR8tJ9Scw3,iv:UjMUqgb9afOePsCo3LZHz1E+cKUOSpmlrFlPMKMKRos=,tag:WDAsxL/3odduQkVBKp1Rpw==,type:str]
    MONGO_DB_PORT: ENC[AES256_GCM,data:zyU9YlY=,iv:qofla/FlLINtXp1n+C4XFP+HNx4ZlvsleFgKeYI2Eeo=,tag:TMfnn1H0Gi2QtPIiNX/Nrw==,type:str]
    MONGO_USER: ENC[AES256_GCM,data:wQEJidI=,iv:lcpBKAqBAtgD5Vo8kiUlhbeVTRqoivBzdxaONrBCKxo=,tag:d4kyj5LOeE3Y/tR7cy0jQg==,type:str]
    MONGO_PASSWORD: ENC[AES256_GCM,data:/OaWmkKw,iv:CXl0LToTPpQfkQnPI8hkzryCGs7p1fRhjvbOohsexEs=,tag:wqx5kCcP2o6+Evmhd7EStg==,type:str]
    MONGO_DB_NAME: ENC[AES256_GCM,data:Ayn56lX8,iv:Y/WyHK4G0X2j51VAVgBF78fGUTXhHO/JkYdV0d2cF4U=,tag:8bzwwO/0lULQzoefKWj4mQ==,type:str]
sops:
    age:
        - recipient: age1dns2gwpv07g83js3vuqazvlgrwzm78h75hd3xcxqrtwwmsdjsglsu42s0v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCK2w0Q2NnZjFuSzdwQjlF
            dlRtT0c1dTVUZ2YyMGRyV05JL1lJM0FoMzNjCjBsekl4WWxRRVVmTFJ2dDMzM3h5
            VjZuNzQreVoweG0wek1tNUZSempxc2sKLS0tIFJLcDBuQ1JoVHJkQW5CWXQyZjl5
            L2ZNaDFTREpURUo3b3NDektTUDQ4R3MKNhLLAeqNUP7wcbHC850mVCuhT+AMJP3O
            0Cn6fKUUhoXUxG6rbyuMiYim+jLkxVBWMIoIgH50sbMwoS20pDwBAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T13:51:23Z"
    mac: ENC[AES256_GCM,data:T4YxnzAcnAjkypqWlGHU1Lq5b4jbOWR7jnScNUaShVz/ykS8OFfTw9FLUzLUgKxl1/ZiTbPTjNg4suAYdQ3zCbw5x1HjCHctAoMUTxCKAQx92QMx4bpc15mj0vzmHS1rxqjSbzeggX8rtm2yI+VRV/m7Tcc7jOFlSYrz90fQKOc=,iv:SSka7uKjduBf9r82CwoGlNVCHx/1Z4GXq4UnUE/LTsc=,tag:NKs13oblK5MwohSx78mCzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
