apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  MONGO_DB_HOST: "localhost"
  MONGO_DB_PORT: "32017"
  MONGO_USER: "admin"
  MONGO_PASSWORD: "secret"
  MONGO_DB_NAME: "elogdb"
